p8105\_hw6\_hn2339
================
Haowei Ni
2018/11/18

``` r
library(tidyverse)
```

    ## ─ Attaching packages ──────────────────── tidyverse 1.2.1 ─

    ## ✔ ggplot2 3.0.0     ✔ purrr   0.2.5
    ## ✔ tibble  1.4.2     ✔ dplyr   0.7.8
    ## ✔ tidyr   0.8.1     ✔ stringr 1.3.1
    ## ✔ readr   1.1.1     ✔ forcats 0.3.0

    ## ─ Conflicts ───────────────────── tidyverse_conflicts() ─
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(dplyr)
library(stringr)
library(readr)
```

Question 1
----------

``` r
library(readr)
homicide = read_csv("data/homicide-data.csv") %>% 
  janitor::clean_names()
```

    ## Parsed with column specification:
    ## cols(
    ##   uid = col_character(),
    ##   reported_date = col_integer(),
    ##   victim_last = col_character(),
    ##   victim_first = col_character(),
    ##   victim_race = col_character(),
    ##   victim_age = col_character(),
    ##   victim_sex = col_character(),
    ##   city = col_character(),
    ##   state = col_character(),
    ##   lat = col_double(),
    ##   lon = col_double(),
    ##   disposition = col_character()
    ## )

Create a city\_state variable and a binary variable

``` r
homicide = 
  homicide %>% 
  mutate(city_state = str_c(city, state, sep = "_"),  
         resolved = as.numeric(disposition == "Closed by arrest"))
```

Omit city Dallas, TX; Phoenix, AZ; and Kansas City, MO and Tulsa, AL

``` r
homicide = 
  homicide %>% 
  filter(!(city_state == "Dallas_TX" | city_state == "Phoenix_AZ" | city_state == "Kansas City_MO" | city_state == "Tulsa_AL")) %>% 
  mutate(victim_race = fct_relevel(ifelse(victim_race == "White", "white", "non-white"), "white"))
```

Modifiy victim\_race, and make victim\_age numeric

``` r
homicide = 
  homicide %>%
  mutate(victim_age = as.numeric(victim_age),
         victim_race = fct_relevel(victim_race, "White"))
```

    ## Warning in evalq(as.numeric(victim_age), <environment>): 强制改变过程中产生
    ## 了NA

    ## Warning: Unknown levels in `f`: White

fit a logistic regression

``` r
baltimore_df = 
  homicide %>% 
  filter(city == "Baltimore")
```

``` r
fit_logistic = 
  baltimore_df %>% 
  glm(resolved ~ victim_age + victim_race + victim_sex, data = ., family = binomial())
```

obtain the estimate and confidence interval of the adjusted odds ratio

``` r
fit_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate), # transform back
         lower_bound = exp(estimate - std.error*1.96),
         upper_bound = exp(estimate + std.error*1.96)) %>%
  select(term, log_OR = estimate, OR, lower_bound, upper_bound, p.value) %>% 
  knitr::kable(digits = 3)
```

| term                  |  log\_OR|     OR|  lower\_bound|  upper\_bound|  p.value|
|:----------------------|--------:|------:|-------------:|-------------:|--------:|
| (Intercept)           |    1.186|  3.274|         2.067|         5.186|    0.000|
| victim\_age           |   -0.007|  0.993|         0.987|         0.999|    0.032|
| victim\_racenon-white |   -0.820|  0.441|         0.313|         0.620|    0.000|
| victim\_sexMale       |   -0.888|  0.412|         0.315|         0.537|    0.000|

the odds ratio estimate is 0.441 and 95% CI is (0.313, 0.620)

``` r
homicide_all =
  homicide %>% 
  group_by(city_state) %>% 
  nest()
OR_plot =
  homicide_all %>% 
  mutate(models = map(data, ~glm(resolved ~ victim_age + victim_sex + victim_race, data = .x, family = binomial())),
    models = map(models, broom::tidy)) %>% 
  select(-data) %>% 
  unnest() %>% 
  filter(term == "victim_racenon-white") %>% 
  mutate(OR = exp(estimate),
         lower_bound = exp(estimate - std.error*1.96),
         upper_bound = exp(estimate + std.error*1.96)) 
```

``` r
OR_plot %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point() + 
  geom_errorbar(aes(ymin = lower_bound, ymax = upper_bound)) +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.text.x = element_text(angle = 90, size = 8),
        legend.key.size = unit(0.05, "cm"))
```

![](p8105_hw6_hn2339_files/figure-markdown_github/unnamed-chunk-10-1.png)

From this plot, we can see that Boston\_MA has the lowest OR means that the non-white people's case and the white people's case are the same level difficulty to resolve.Tampa\_FL has the highest OR means that non-white people's cases are much in the same solving rate as the white people. There are no much difference. Some cities have large error bar means that the there are much influction in the rate of solving the cases.
