---
title: "p8105_hw6_hn2339"
author: "Haowei Ni"
date: "2018/11/18"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(dplyr)
library(stringr)
library(readr)
```

## Question 1

```{r}
library(readr)
homicide = read_csv("data/homicide-data.csv") %>% 
  janitor::clean_names()
```

Create a city_state variable and a binary variable 

```{r}
homicide = 
  homicide %>% 
  mutate(city_state = str_c(city, state, sep = "_"),  
         resolved = as.numeric(disposition == "Closed by arrest"))
```

Omit city Dallas, TX; Phoenix, AZ; and Kansas City, MO and Tulsa, AL

```{r}
homicide = 
  homicide %>% 
  filter(!(city_state == "Dallas_TX" | city_state == "Phoenix_AZ" | city_state == "Kansas City_MO" | city_state == "Tulsa_AL")) %>% 
  mutate(victim_race = fct_relevel(ifelse(victim_race == "White", "white", "non-white"), "white"))
```

Modifiy victim_race, and make victim_age numeric

```{r}
homicide = 
  homicide %>%
  mutate(victim_age = as.numeric(victim_age),
         victim_race = fct_relevel(victim_race, "White"))
```

fit a logistic regression

```{r}
baltimore_df = 
  homicide %>% 
  filter(city == "Baltimore")
```

```{r}
fit_logistic = 
  baltimore_df %>% 
  glm(resolved ~ victim_age + victim_race + victim_sex, data = ., family = binomial())
```

obtain the estimate and confidence interval of the adjusted odds ratio

```{r}
fit_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate), # transform back
         lower_bound = exp(estimate - std.error*1.96),
         upper_bound = exp(estimate + std.error*1.96)) %>%
  select(term, log_OR = estimate, OR, lower_bound, upper_bound, p.value) %>% 
  knitr::kable(digits = 3)
```



